[package]
name = "poker_game"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
poker = "0x8f7f993b8e2946e61dbe55c194fb740afe0b5a2088779c12bca8149a3a6c769e"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "randomnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "randomnet", subdir = "aptos-move/framework/aptos-token-objects" }