name: "Move Tests"
on:
  pull_request:
  push:
    branches:
      - main
      - testnet
      - mainnet

jobs:
  move-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dev dependencies.
        run: ./move/sh_scripts/dev_setup.sh
      - name: Runs move tests.
        run: ./move/sh_scripts/move_tests.sh
